import {TrendingUp, Eye, Wrench, AccessibilityIcon } from 'lucide-react';
export const products = [
    {
        id: 1,
        name: 'Access Patronus',
        description: 'Access Patronus is a powerful access management tool designed to simplify and streamline how teams manage infrastructure-level access in AWS. \n With Access Patronus, you can securely grant and revoke temporary access to critical resources, ensuring just-in-time privileges and better compliance across your cloud ecosystem.',
        category: 'Access Management',
        repoName: 'access-patronus',
        icon: AccessibilityIcon,
        technologies: ['Go', 'Makefile'],
        features: ['Ec2 Access Control', 'Role Access Control', 'Database Access Control'],
        gradient: 'blue',
        released: false,
        stars: 0,
        forks: 0,
        contributors: 0,
        downloads: 0
    },
    {
        id: 2,
        name: 'Vision',
        description: 'Vision is a developer-friendly logging library designed to help you create meaningful, structured, and searchable logs — not just lines in the console.\nBuilt with clarity, performance, and observability in mind, Vision enables teams to produce consistent logs that are easy to filter, trace, and debug, even in distributed systems.',
        category: 'Logging',
        icon: Eye,
        technologies: ['JavaScript'],
        features: ['Logging', 'Structured Logging', 'Searchable Logs', 'Observability'],
        gradient: 'green',
        released: false,
        stars: 0,
        forks: 0,
        contributors: 0,
        downloads: 0
    },
    {
        id: 3,
        name: 'Mistri',
        description: 'Mistri is a modern tool that helps you scaffold production-ready repositories and provision essential cloud infrastructure — all in one go.\nWhether you are spinning up a microservice, frontend app, or data pipeline, Mistri takes care of the heavy lifting by combining codebase generation with resource setup in AWS.',
        category: 'Infrastructure Automation',
        icon: Wrench,
        technologies: ['Go'],
        features: ['Repository Scaffolding', 'AWS Resource Provisioning', 'Plug-and-Play Templates'],
        gradient: 'blue',
        released: false,
        stars: 0,
        forks: 0,
        contributors: 0,
        downloads: 0
    },
    {
        id: 3,
        name: 'ScalerX',
        description: 'ScalerX is an automation-first infrastructure scaler built to help teams dynamically manage resource usage across their cloud stack. Whether you are running EC2 with Auto Scaling Groups, relational databases on RDS, workloads on Kubernetes, or in-memory caching with Redis — ZenScale brings it all under one simple, scriptable interface.',
        category: 'Infrastructure Automation',
        icon: TrendingUp,
        technologies: ['Python'],
        features: ['Smart Scaling', 'Manual + Auto Modes', 'Slack/Email Alertss'],
        gradient: 'green',
        released: false,
        stars: 0,
        forks: 0,
        contributors: 0,
        downloads: 0
    },
];